language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake test
  - bundle exec codeclimate-test-reporter
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
addons:
    code_climate:
        repo_token: ac1640edaefa720557e56bfaba4e09808559d7d61812f96d58ea4aa5f4669738
